fc_grandforest:
  files:
    expression_data: expression_data.csv
    interaction_network: interaction_network.csv
    local_model_output: local_model.RData
    global_model_output: global_model.RData